name: Secret Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

        run: |
          echo "Secret Loaded"
          echo $MY_SECRET